name = Front
description = Front - A layout for the frontpage, based on Classic
preview = preview.png
template = front-layout

; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted]    = Highlighted
regions[help] = Help
regions[content] = Content ;Wordt enkel gebruikt om metatag op homepage te renderen
regions[footer]         = Footer
regions[footer_copyright] = Footer copyright
regions[cookie_law] = Cookie law message


; ========================================
; Homepage extra regions
; ========================================
;regions[home_showcase] = Homepage showcase
;regions[home_intro_left] = Home intro left
;regions[home_intro_right] = Home intro right
;regions[home_content] = Home content

; ========================================
; Stylesheets
; ========================================
stylesheets[all][] = css/layouts/front/front.layout.css
stylesheets[all][] = css/layouts/front/front.layout.no-query.css
