name = Classic
description = A classic layout featuring a topbar, header, 3 cols and footer
preview = preview.png
template = classic-layout

; ========================================
; Regions
; ========================================
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer
regions[footer_copyright] = Footer copyright
regions[cookie_law] = Cookie law message

; Stylesheets
stylesheets[all][] = css/layouts/classic/classic.layout.css
stylesheets[all][] = css/layouts/classic/classic.layout.no-query.css