<?php
/**
 * @file
 * fo2_base.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function fo2_base_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['fo2_block-o2_block_550a1eeb-216a-44cf-8282-e073e382f570'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'o2_block_550a1eeb-216a-44cf-8282-e073e382f570',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'fo2_block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'expe_omega' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'expe_omega',
        'weight' => 0,
      ),
      'omega_o2' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'omega_o2',
        'weight' => -12,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['fo2_block-o2_block_96a66101-9daa-4fe6-a4ad-957b35e43c17'] = array(
    'cache' => 1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'o2_block_96a66101-9daa-4fe6-a4ad-957b35e43c17',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'fo2_block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'expe_omega' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'expe_omega',
        'weight' => 0,
      ),
      'omega_o2' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'omega_o2',
        'weight' => -11,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['locale-language'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'language',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'locale',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'expe_omega' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'expe_omega',
        'weight' => -16,
      ),
      'omega_o2' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'omega_o2',
        'weight' => -17,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['menu_block-1'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 1,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu_block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'expe_omega' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'expe_omega',
        'weight' => -15,
      ),
      'omega_o2' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'omega_o2',
        'weight' => -16,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '<none>',
    'visibility' => 0,
  );

  $export['menu_block-2'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 2,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu_block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'expe_omega' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'expe_omega',
        'weight' => -14,
      ),
      'omega_o2' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'omega_o2',
        'weight' => -15,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '<none>',
    'visibility' => 0,
  );

  $export['menu_block-3'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 3,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu_block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'expe_omega' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'expe_omega',
        'weight' => -13,
      ),
      'omega_o2' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'omega_o2',
        'weight' => -14,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '<none>',
    'visibility' => 0,
  );

  $export['menu_block-4'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 4,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu_block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'expe_omega' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'expe_omega',
        'weight' => 1,
      ),
      'omega_o2' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'omega_o2',
        'weight' => 2,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '<none>',
    'visibility' => 0,
  );

  $export['menu_block-5'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 5,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu_block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'expe_omega' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'expe_omega',
        'weight' => -20,
      ),
      'omega_o2' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'omega_o2',
        'weight' => -20,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '<none>',
    'visibility' => 0,
  );

  $export['menu_block-6'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 6,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu_block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'expe_omega' => array(
        'region' => 'navigation',
        'status' => 1,
        'theme' => 'expe_omega',
        'weight' => 0,
      ),
      'omega_o2' => array(
        'region' => 'navigation',
        'status' => 1,
        'theme' => 'omega_o2',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '<none>',
    'visibility' => 0,
  );

  $export['menu_block-7'] = array(
    'cache' => -1,
    'css_class' => 'footer-services',
    'custom' => 0,
    'delta' => 7,
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'menu_block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'expe_omega' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'expe_omega',
        'weight' => -22,
      ),
      'omega_o2' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'omega_o2',
        'weight' => -3,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '<none>',
    'visibility' => 0,
  );

  return $export;
}
